// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCrawlByID(arg1) {
  return window['go']['main']['App']['DeleteCrawlByID'](arg1);
}

export function DeleteProjectByID(arg1) {
  return window['go']['main']['App']['DeleteProjectByID'](arg1);
}

export function GetConfigForDomain(arg1) {
  return window['go']['main']['App']['GetConfigForDomain'](arg1);
}

export function GetCrawlWithResults(arg1) {
  return window['go']['main']['App']['GetCrawlWithResults'](arg1);
}

export function GetCrawls(arg1) {
  return window['go']['main']['App']['GetCrawls'](arg1);
}

export function GetFaviconData(arg1) {
  return window['go']['main']['App']['GetFaviconData'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function StartCrawl(arg1) {
  return window['go']['main']['App']['StartCrawl'](arg1);
}

export function UpdateConfigForDomain(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConfigForDomain'](arg1, arg2, arg3);
}
