// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteCrawlByID(arg1:number):Promise<void>;

export function DeleteProjectByID(arg1:number):Promise<void>;

export function GetActiveCrawlData(arg1:number):Promise<main.CrawlResultDetailed>;

export function GetActiveCrawls():Promise<Array<main.CrawlProgress>>;

export function GetConfigForDomain(arg1:string):Promise<main.ConfigResponse>;

export function GetCrawlWithResults(arg1:number):Promise<main.CrawlResultDetailed>;

export function GetCrawls(arg1:number):Promise<Array<main.CrawlInfo>>;

export function GetFaviconData(arg1:string):Promise<string>;

export function GetProjects():Promise<Array<main.ProjectInfo>>;

export function StartCrawl(arg1:string):Promise<void>;

export function StopCrawl(arg1:number):Promise<void>;

export function UpdateConfigForDomain(arg1:string,arg2:boolean,arg3:number,arg4:boolean,arg5:boolean,arg6:Array<string>):Promise<void>;
