// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['DesktopApp']['CheckForUpdate']();
}

export function CheckSystemHealth() {
  return window['go']['main']['DesktopApp']['CheckSystemHealth']();
}

export function DeleteCrawlByID(arg1) {
  return window['go']['main']['DesktopApp']['DeleteCrawlByID'](arg1);
}

export function DeleteProjectByID(arg1) {
  return window['go']['main']['DesktopApp']['DeleteProjectByID'](arg1);
}

export function DetectJSRenderingNeed(arg1) {
  return window['go']['main']['DesktopApp']['DetectJSRenderingNeed'](arg1);
}

export function DownloadAndInstallUpdate() {
  return window['go']['main']['DesktopApp']['DownloadAndInstallUpdate']();
}

export function GetAICrawlerData(arg1) {
  return window['go']['main']['DesktopApp']['GetAICrawlerData'](arg1);
}

export function GetActiveCrawlStats(arg1) {
  return window['go']['main']['DesktopApp']['GetActiveCrawlStats'](arg1);
}

export function GetActiveCrawls() {
  return window['go']['main']['DesktopApp']['GetActiveCrawls']();
}

export function GetConfigForDomain(arg1) {
  return window['go']['main']['DesktopApp']['GetConfigForDomain'](arg1);
}

export function GetCrawlStats(arg1) {
  return window['go']['main']['DesktopApp']['GetCrawlStats'](arg1);
}

export function GetCrawlWithResultsPaginated(arg1, arg2, arg3, arg4) {
  return window['go']['main']['DesktopApp']['GetCrawlWithResultsPaginated'](arg1, arg2, arg3, arg4);
}

export function GetCrawls(arg1) {
  return window['go']['main']['DesktopApp']['GetCrawls'](arg1);
}

export function GetFaviconData(arg1) {
  return window['go']['main']['DesktopApp']['GetFaviconData'](arg1);
}

export function GetPageContent(arg1, arg2) {
  return window['go']['main']['DesktopApp']['GetPageContent'](arg1, arg2);
}

export function GetPageLinksForURL(arg1, arg2) {
  return window['go']['main']['DesktopApp']['GetPageLinksForURL'](arg1, arg2);
}

export function GetProjects() {
  return window['go']['main']['DesktopApp']['GetProjects']();
}

export function GetServerStatus() {
  return window['go']['main']['DesktopApp']['GetServerStatus']();
}

export function GetVersion() {
  return window['go']['main']['DesktopApp']['GetVersion']();
}

export function RunAICrawlerChecks(arg1) {
  return window['go']['main']['DesktopApp']['RunAICrawlerChecks'](arg1);
}

export function SaveAICrawlerData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['DesktopApp']['SaveAICrawlerData'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchCrawlResultsPaginated(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['DesktopApp']['SearchCrawlResultsPaginated'](arg1, arg2, arg3, arg4, arg5);
}

export function StartCrawl(arg1) {
  return window['go']['main']['DesktopApp']['StartCrawl'](arg1);
}

export function StartServerWithTunnel() {
  return window['go']['main']['DesktopApp']['StartServerWithTunnel']();
}

export function Startup(arg1) {
  return window['go']['main']['DesktopApp']['Startup'](arg1);
}

export function StopCrawl(arg1) {
  return window['go']['main']['DesktopApp']['StopCrawl'](arg1);
}

export function StopServerWithTunnel() {
  return window['go']['main']['DesktopApp']['StopServerWithTunnel']();
}

export function UpdateConfigForDomain(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18) {
  return window['go']['main']['DesktopApp']['UpdateConfigForDomain'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18);
}
