// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function CheckForUpdate():Promise<types.UpdateInfo>;

export function DeleteCrawlByID(arg1:number):Promise<void>;

export function DeleteProjectByID(arg1:number):Promise<void>;

export function DetectJSRenderingNeed(arg1:string):Promise<boolean>;

export function DownloadAndInstallUpdate():Promise<void>;

export function GetActiveCrawlData(arg1:number):Promise<types.CrawlResultDetailed>;

export function GetActiveCrawls():Promise<Array<types.CrawlProgress>>;

export function GetAllFrameworks():Promise<Array<types.FrameworkInfo>>;

export function GetConfigForDomain(arg1:string):Promise<types.ConfigResponse>;

export function GetCrawlWithResults(arg1:number):Promise<types.CrawlResultDetailed>;

export function GetCrawls(arg1:number):Promise<Array<types.CrawlInfo>>;

export function GetDomainFramework(arg1:number,arg2:string):Promise<types.DomainFrameworkResponse>;

export function GetDomainFrameworks(arg1:number):Promise<Array<types.DomainFrameworkResponse>>;

export function GetFaviconData(arg1:string):Promise<string>;

export function GetPageContent(arg1:number,arg2:string):Promise<string>;

export function GetPageLinksForURL(arg1:number,arg2:string):Promise<types.PageLinksResponse>;

export function GetProjects():Promise<Array<types.ProjectInfo>>;

export function GetServerStatus():Promise<types.ServerStatus>;

export function GetVersion():Promise<string>;

export function SetDomainFramework(arg1:number,arg2:string,arg3:string):Promise<void>;

export function StartCrawl(arg1:string):Promise<void>;

export function StartServerWithTunnel():Promise<types.ServerInfo>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopCrawl(arg1:number):Promise<void>;

export function StopServerWithTunnel():Promise<void>;

export function UpdateConfigForDomain(arg1:string,arg2:boolean,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string,arg8:boolean,arg9:boolean,arg10:boolean,arg11:Array<string>,arg12:boolean,arg13:boolean):Promise<void>;
