// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['DesktopApp']['CheckForUpdate']();
}

export function DeleteCrawlByID(arg1) {
  return window['go']['main']['DesktopApp']['DeleteCrawlByID'](arg1);
}

export function DeleteProjectByID(arg1) {
  return window['go']['main']['DesktopApp']['DeleteProjectByID'](arg1);
}

export function DownloadAndInstallUpdate() {
  return window['go']['main']['DesktopApp']['DownloadAndInstallUpdate']();
}

export function GetActiveCrawlData(arg1) {
  return window['go']['main']['DesktopApp']['GetActiveCrawlData'](arg1);
}

export function GetActiveCrawls() {
  return window['go']['main']['DesktopApp']['GetActiveCrawls']();
}

export function GetConfigForDomain(arg1) {
  return window['go']['main']['DesktopApp']['GetConfigForDomain'](arg1);
}

export function GetCrawlWithResults(arg1) {
  return window['go']['main']['DesktopApp']['GetCrawlWithResults'](arg1);
}

export function GetCrawls(arg1) {
  return window['go']['main']['DesktopApp']['GetCrawls'](arg1);
}

export function GetFaviconData(arg1) {
  return window['go']['main']['DesktopApp']['GetFaviconData'](arg1);
}

export function GetPageLinksForURL(arg1, arg2) {
  return window['go']['main']['DesktopApp']['GetPageLinksForURL'](arg1, arg2);
}

export function GetProjects() {
  return window['go']['main']['DesktopApp']['GetProjects']();
}

export function GetVersion() {
  return window['go']['main']['DesktopApp']['GetVersion']();
}

export function StartCrawl(arg1) {
  return window['go']['main']['DesktopApp']['StartCrawl'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['DesktopApp']['Startup'](arg1);
}

export function StopCrawl(arg1) {
  return window['go']['main']['DesktopApp']['StopCrawl'](arg1);
}

export function UpdateConfigForDomain(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['DesktopApp']['UpdateConfigForDomain'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
