// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function CheckForUpdate():Promise<types.UpdateInfo>;

export function DeleteCrawlByID(arg1:number):Promise<void>;

export function DeleteProjectByID(arg1:number):Promise<void>;

export function DetectJSRenderingNeed(arg1:string):Promise<boolean>;

export function DownloadAndInstallUpdate():Promise<void>;

export function GetAICrawlerData(arg1:string):Promise<types.AICrawlerResponse>;

export function GetActiveCrawlStats(arg1:number):Promise<types.ActiveCrawlStats>;

export function GetActiveCrawls():Promise<Array<types.CrawlProgress>>;

export function GetConfigForDomain(arg1:string):Promise<types.ConfigResponse>;

export function GetCrawlStats(arg1:number):Promise<types.ActiveCrawlStats>;

export function GetCrawlWithResultsPaginated(arg1:number,arg2:number,arg3:number,arg4:string):Promise<types.CrawlResultPaginated>;

export function GetCrawls(arg1:number):Promise<Array<types.CrawlInfo>>;

export function GetFaviconData(arg1:string):Promise<string>;

export function GetPageContent(arg1:number,arg2:string):Promise<string>;

export function GetPageLinksForURL(arg1:number,arg2:string):Promise<types.PageLinksResponse>;

export function GetProjects():Promise<Array<types.ProjectInfo>>;

export function GetServerStatus():Promise<types.ServerStatus>;

export function GetVersion():Promise<string>;

export function RunAICrawlerChecks(arg1:string):Promise<void>;

export function SaveAICrawlerData(arg1:string,arg2:types.AICrawlerData,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SearchCrawlResultsPaginated(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<types.CrawlResultPaginated>;

export function StartCrawl(arg1:string):Promise<void>;

export function StartServerWithTunnel():Promise<types.ServerInfo>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopCrawl(arg1:number):Promise<void>;

export function StopServerWithTunnel():Promise<void>;

export function UpdateConfigForDomain(arg1:string,arg2:boolean,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string,arg8:boolean,arg9:boolean,arg10:boolean,arg11:Array<string>,arg12:boolean,arg13:boolean,arg14:string,arg15:boolean,arg16:boolean,arg17:boolean,arg18:boolean):Promise<void>;
