// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function CheckForUpdate():Promise<types.UpdateInfo>;

export function DeleteCrawlByID(arg1:number):Promise<void>;

export function DeleteProjectByID(arg1:number):Promise<void>;

export function DownloadAndInstallUpdate():Promise<void>;

export function GetActiveCrawlData(arg1:number):Promise<types.CrawlResultDetailed>;

export function GetActiveCrawls():Promise<Array<types.CrawlProgress>>;

export function GetConfigForDomain(arg1:string):Promise<types.ConfigResponse>;

export function GetCrawlWithResults(arg1:number):Promise<types.CrawlResultDetailed>;

export function GetCrawls(arg1:number):Promise<Array<types.CrawlInfo>>;

export function GetFaviconData(arg1:string):Promise<string>;

export function GetPageContent(arg1:number,arg2:string):Promise<string>;

export function GetPageLinksForURL(arg1:number,arg2:string):Promise<types.PageLinksResponse>;

export function GetProjects():Promise<Array<types.ProjectInfo>>;

export function GetServerStatus():Promise<types.ServerStatus>;

export function GetVersion():Promise<string>;

export function StartCrawl(arg1:string):Promise<void>;

export function StartServerWithTunnel():Promise<types.ServerInfo>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopCrawl(arg1:number):Promise<void>;

export function StopServerWithTunnel():Promise<void>;

export function UpdateConfigForDomain(arg1:string,arg2:boolean,arg3:number,arg4:string,arg5:boolean,arg6:boolean,arg7:boolean,arg8:Array<string>,arg9:boolean):Promise<void>;
