//go:build ignore

// Command gen_hierarchy regenerates schemaorg_hierarchy.txt — the embedded
// schema.org type IS-A graph used for rich-result subtype resolution — from
// schema.org's authoritative published types CSV.
//
// Usage: go generate ./internal/structured/   (needs network access)
//
// The output is intentionally minimal (child<TAB>parent[,parent...]); it carries
// no curation. The curated rich-result root set lives in structured.go's
// `requirements` map, and resolution picks the most-specific curated ancestor at
// validation time, so refreshing this file never changes which types are
// rich-result roots — only the IS-A edges between them.
package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
)

const source = "https://schema.org/version/latest/schemaorg-current-https-types.csv"

func main() {
	resp, err := http.Get(source)
	if err != nil {
		fail(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		fail(fmt.Errorf("GET %s: %s", source, resp.Status))
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		fail(err)
	}

	r := csv.NewReader(strings.NewReader(string(body)))
	rows, err := r.ReadAll()
	if err != nil {
		fail(err)
	}
	if len(rows) == 0 {
		fail(fmt.Errorf("empty CSV"))
	}
	header := rows[0]
	col := func(name string) int {
		for i, h := range header {
			if h == name {
				return i
			}
		}
		fail(fmt.Errorf("column %q not found", name))
		return -1
	}
	labelCol, supCol := col("label"), col("subTypeOf")

	type edge struct {
		child   string
		parents []string
	}
	var edges []edge
	for _, row := range rows[1:] {
		label := strings.TrimSpace(row[labelCol])
		var parents []string
		for _, p := range strings.Split(row[supCol], ",") {
			p = strings.TrimSpace(p)
			if p == "" {
				continue
			}
			if i := strings.LastIndexByte(p, '/'); i >= 0 {
				p = p[i+1:]
			}
			parents = append(parents, p)
		}
		if label != "" && len(parents) > 0 {
			edges = append(edges, edge{label, parents})
		}
	}
	sort.Slice(edges, func(i, j int) bool { return edges[i].child < edges[j].child })

	var b strings.Builder
	b.WriteString("# schema.org type IS-A graph (child<TAB>parent[,parent...]).\n")
	b.WriteString("# Source: " + source + "\n")
	b.WriteString("# Regenerated by gen_hierarchy.go via `go generate ./internal/structured/`.\n")
	b.WriteString("# Objective subClassOf edges only — no curation; the curated rich-result\n")
	b.WriteString("# root set lives in structured.go `requirements`, and resolution picks the\n")
	b.WriteString("# most-specific curated ancestor at validation time.\n")
	for _, e := range edges {
		b.WriteString(e.child + "\t" + strings.Join(e.parents, ",") + "\n")
	}
	if err := os.WriteFile("schemaorg_hierarchy.txt", []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote schemaorg_hierarchy.txt (%d edges)\n", len(edges))
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen_hierarchy:", err)
	os.Exit(1)
}
