// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteCrawlByID(arg1:number):Promise<void>;

export function DeleteProjectByID(arg1:number):Promise<void>;

export function GetConfigForDomain(arg1:string):Promise<main.Config>;

export function GetCrawlWithResults(arg1:number):Promise<main.CrawlResultDetailed>;

export function GetCrawls(arg1:number):Promise<Array<main.CrawlInfo>>;

export function GetProjects():Promise<Array<main.ProjectInfo>>;

export function StartCrawl(arg1:string):Promise<void>;

export function UpdateConfigForDomain(arg1:string,arg2:boolean,arg3:number):Promise<void>;
