// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfigForDomain(arg1:string):Promise<main.Config>;

export function StartCrawl(arg1:string):Promise<void>;

export function UpdateConfigForDomain(arg1:string,arg2:boolean,arg3:number):Promise<void>;
